version: '3'
services:
    app:
        container_name: game-stats-tracker-api
        build:
            context: .
            target: ${NODE_ENV}
        env_file:
            - ./.env
        environment:
            PORT: ${PORT}
            MONGO_DB_URI: ${MONGO_DB_URI}
            SECRET: ${SECRET}
            JWT_SECRET: ${JWT_SECRET}
        networks:
            - game-stats-tracker-api
        volumes:
            - .:/node/app
            - /node/app/node_modules
        ports:
            - '3000:3000'
        command: ['node', 'dist/index.js']

networks:
    game-stats-tracker-api:
        driver: bridge
