POST https://game-stats-tracker-api.fly.dev/api/league/invite/67dc044390b25dc828fbbc48
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibWlra2kiLCJ1c2VybmFtZSI6Im1pa2tpaGlpcmkiLCJpZCI6IjY3ZGMwM2Y5OTBiMjVkYzgyOGZiYmM0MyIsImlhdCI6MTc0MjQ3MjI4OSwiZXhwIjoxNzQ1MDY0Mjg5fQ.JKq6tKz_23Hcy9C5SKKx2stQGf1RzZ2s61lHhMGcK2E