DELETE http://localhost:3000/api/league/remove-game/67cd5ce6776611125e102fc8/67cd65a3df17526f44d1637c
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidXNlckBleGFtcGxlLmNvbSIsInVzZXJuYW1lIjoiaGVzc3VIb3BvIiwiaWQiOiI2N2M5Y2U0ZmQ0MTVkZjg5Nzk0ZjBlY2QiLCJpYXQiOjE3NDE1MTEyMjgsImV4cCI6MTc0MTUxNDgyOH0.KckSoOTpJxtyuY8I1xSc7xmBDUOzsv-JKJt-0_9LK2c