DELETE http://localhost:3000/api/league/remove-game/67d2dbe06f5c2dd262b34b7b/67d2ec22d9b318e61b294023
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibWlra2loaWlyaUBtaWtraWhpaXJpLmNvbSIsInVzZXJuYW1lIjoiaGVzc3Vob3BvIiwiaWQiOiI2N2QyZDg4OWQ4MzkxNGU3NmU2ZDIxNWQiLCJtYXRjaGVzIjpbeyJfaWQiOiI2N2QyZTIzMzNmNzkzMzBlY2E4ZWY1NWEifSx7Il9pZCI6IjY3ZDJlMmVkNGQxYjhiYTYyNDJkM2RiOCJ9LHsiX2lkIjoiNjdkMmUzMWI4OTU3MTk0OTg5NWEyMjNlIn0seyJfaWQiOiI2N2QyZTkwMWU4ODFjZGFkMTVmNjVjZTAifV0sImxlYWd1ZXMiOlt7Il9pZCI6IjY3ZDJkOTllZDgzOTE0ZTc2ZTZkMjE3MSJ9LHsiX2lkIjoiNjdkMmRiNGZlZjgzNmZkOTMxOWQ2NzAzIn0seyJfaWQiOiI2N2QyZGJlMDZmNWMyZGQyNjJiMzRiN2YifV0sImlhdCI6MTc0MTg3NTQ4MCwiZXhwIjoxNzQxODc5MDgwfQ.21IUrJ0fzju6Po3s2wnqmcmOdvO-8yPBf_YU0lMiSxg