POST http://localhost:3000/api/game
Content-Type: application/json

{
   "gameType": "NHL",
   "league": "67d30c3ef5f808958baa4e94",
   "homeTeam": "Toronto Maple Leafs",
   "awayTeam": "Montreal Canadiens",
   "homePlayer": "mikkihiiri",
   "awayPlayer": "hessuhopo",
   "homeScore": 3,
   "awayScore": 2,
   "createdAt": "2025-03-05T19:30:00Z",
   "overTime": false,
   "penalties": false
}
