POST http://localhost:3000/api/league
Content-Type: application/json

{
    "name": "Champions League",
    "gameTypes": ["FIFA"],
    "admins": ["hessuhopo", "mikkihiiri"],
    "users": [
        "hessuhopo",
        "mikkihiiri"
    ],
    "duration": "2025-12-31T23:59:59.000Z"
}
