POST http://localhost:3000/api/league/user/67d2dbe06f5c2dd262b34b7b
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibWlra2loaWlyaUBtaWtraWhpaXJpLmNvbSIsInVzZXJuYW1lIjoiaGVzc3Vob3BvIiwiaWQiOiI2N2QyZDg4OWQ4MzkxNGU3NmU2ZDIxNWQiLCJtYXRjaGVzIjpbeyJfaWQiOiI2N2QyZWFhYjg2NTc0YTg2ZWM5NmM4NDQiLCJnYW1lVHlwZSI6IkZJRkEiLCJsZWFndWUiOiI2N2QyZGJlMDZmNWMyZGQyNjJiMzRiN2IiLCJob21lVGVhbSI6IlJlYWwgTWFkcmlkIiwiYXdheVRlYW0iOiJQU0ciLCJob21lU2NvcmUiOjMsImF3YXlTY29yZSI6MiwiaG9tZVBsYXllciI6IjY3ZDJkODg5ZDgzOTE0ZTc2ZTZkMjE1ZCIsImF3YXlQbGF5ZXIiOiI2N2QyZDg4NGQ4MzkxNGU3NmU2ZDIxNWIiLCJvdmVyVGltZSI6ZmFsc2UsInBlbmFsdGllcyI6ZmFsc2UsImNyZWF0ZWRBdCI6IjIwMjUtMDMtMDVUMTk6MzA6MDAuMDAwWiIsIl9fdiI6MH1dLCJsZWFndWVzIjpbXSwiaWF0IjoxNzQxODgzOTk3LCJleHAiOjE3NDQ0NzU5OTd9.81KIg2I4wQKE-i0dkVD7fVdmw0UvD-YZ9_RJM3KvrKw

{
    "username": "testeri"
}