POST http://localhost:3000/api/game
Content-Type: application/json

{
   "league": "67dc044390b25dc828fbbc48",
   "gameType": "FIFA",
   "homeTeam": "Liverpool",
   "awayTeam": "PSG",
   "homePlayer": "realdestruction",
   "awayPlayer": "mikkihiiri",
   "homeScore": 3,
   "awayScore": 2,
   "createdAt": "2025-03-05T19:30:00Z",
   "overTime": false,
   "penalties": false
}
