DELETE http://localhost:3000/api/league/delete/67cd5ce6776611125e102fc8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidXNlckBleGFtcGxlLmNvbSIsInVzZXJuYW1lIjoiaGVzc3VIb3BvIiwiaWQiOiI2N2M5Y2U0ZmQ0MTVkZjg5Nzk0ZjBlY2QiLCJpYXQiOjE3NDE1Mjg2MjAsImV4cCI6MTc0MTUzMjIyMH0.CbUMUaYVUYF4BZAjxR0JRwwl8_0G1IVlX-OkgXrtSG8