GET http://localhost:3000/api/user/own
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdGVyaSIsInVzZXJuYW1lIjoidGVzdGVyaSIsImlkIjoiNjdkZWE2OWYxZDdlYjQ3MGFhNjUyNDU0IiwiaWF0IjoxNzQ5OTEwNDA0LCJleHAiOjE3NTI1MDI0MDR9.mv2Id3GLoWEUpCzNxwoUcDh_cGTobksoFmTPPujl3Vg

{ }